//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnquiryMaster
    {
        public int Lead_ID { get; set; }
        public Nullable<System.DateTime> LeadDate { get; set; }
        public Nullable<int> SendBy { get; set; }
        public Nullable<int> SendTo { get; set; }
        public string EnquiryType { get; set; }
        public string LeadDescription { get; set; }
        public string SenderName { get; set; }
        public string SenderPhone { get; set; }
        public string SenderEmail { get; set; }
        public string SenderDescription { get; set; }
    }
}
