//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaMaster
    {
        public int mediaID { get; set; }
        public string mediafileName { get; set; }
        public string mediaOriginalName { get; set; }
        public string mediaExtn { get; set; }
        public Nullable<int> mediaSize { get; set; }
        public Nullable<bool> IsDeleated { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
