//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberRegistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberRegistration()
        {
            this.MembersMasters = new HashSet<MembersMaster>();
        }
    
        public int memberRegistration_ID { get; set; }
        public string MemberName { get; set; }
        public string MemeberEmail { get; set; }
        public string MemberPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MembersMaster> MembersMasters { get; set; }
    }
}
