//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class MicroCategory
    {
        public int MicroCat_ID { get; set; }
        public Nullable<int> SubCat_ID { get; set; }
        public string MicroCatName { get; set; }
        public string PageTitle { get; set; }
        public string MetaKeyword { get; set; }
        public string MetaDescription { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual SubCategoryManager SubCategoryManager { get; set; }
    }
}
