//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisiterMaster
    {
        public int Visiter_ID { get; set; }
        public string VisiterName { get; set; }
        public string VisitorEmail { get; set; }
        public string VisitorPhone { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
