//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fixed_Dial_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryMaster()
        {
            this.SubCategoryManagers = new HashSet<SubCategoryManager>();
        }
    
        public int categoryId { get; set; }
        public string categoryName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public Nullable<int> mediaId { get; set; }
        public string pageTitle { get; set; }
        public string metaKeyword { get; set; }
        public string metaDescription { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<int> updatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubCategoryManager> SubCategoryManagers { get; set; }
    }
}
