//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fixed_Dial_API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class indiantr_fixeddialEntities : DbContext
    {
        public indiantr_fixeddialEntities()
            : base("name=indiantr_fixeddialEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryMaster> CategoryMasters { get; set; }
        public virtual DbSet<EnquiryMaster> EnquiryMasters { get; set; }
        public virtual DbSet<MediaMaster> MediaMasters { get; set; }
        public virtual DbSet<MemberRegistration> MemberRegistrations { get; set; }
        public virtual DbSet<MembersMaster> MembersMasters { get; set; }
        public virtual DbSet<MicroCategory> MicroCategories { get; set; }
        public virtual DbSet<ProductServiceMaster> ProductServiceMasters { get; set; }
        public virtual DbSet<SubCategoryManager> SubCategoryManagers { get; set; }
        public virtual DbSet<VisiterMaster> VisiterMasters { get; set; }
    }
}
