//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fixed_Dial_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembersMaster
    {
        public int Member_ID { get; set; }
        public Nullable<int> memberRegID { get; set; }
        public string CompanyName { get; set; }
        public string MemberDesignation { get; set; }
        public string DisplayName { get; set; }
        public string POCName { get; set; }
        public string POCPhoneOne { get; set; }
        public string POCPhoneTwo { get; set; }
        public string TollFreeNumber { get; set; }
        public string FaxNo { get; set; }
        public string Location { get; set; }
        public string Building { get; set; }
        public string Street { get; set; }
        public string Landmark { get; set; }
        public string City { get; set; }
        public string PinCode { get; set; }
        public string MemberState { get; set; }
        public string MemberCountry { get; set; }
        public string Website { get; set; }
        public string GSTIN { get; set; }
        public string PAN { get; set; }
        public string MemberTAN { get; set; }
        public string Profile { get; set; }
        public string EnquiryEmail { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ActivePlanType { get; set; }
        public Nullable<int> MicroCategory { get; set; }
        public string PageTitle { get; set; }
        public string MetaKeyword { get; set; }
        public string MetaDescription { get; set; }
        public string ServiceProviderType { get; set; }
        public string TurnOver { get; set; }
        public string BusinessStatus { get; set; }
        public string Employee { get; set; }
        public Nullable<int> LogoMediaId { get; set; }
        public Nullable<int> BannerImageID { get; set; }
    
        public virtual MemberRegistration MemberRegistration { get; set; }
    }
}
