//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fixed_Dial_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductServiceMaster
    {
        public int PS_ID { get; set; }
        public string Ps_Name { get; set; }
        public Nullable<int> ImageID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string PsDescription { get; set; }
        public string AboutPS { get; set; }
    }
}
