//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fixed_Dial_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategoryManager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubCategoryManager()
        {
            this.MicroCategories = new HashSet<MicroCategory>();
        }
    
        public int SubCat_ID { get; set; }
        public Nullable<int> Cat_ID { get; set; }
        public string SubCatName { get; set; }
        public string PageTitle { get; set; }
        public string MetaKeywork { get; set; }
        public string MedaDescription { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual CategoryMaster CategoryMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MicroCategory> MicroCategories { get; set; }
    }
}
